name: Bug Report
description: If you may have experienced an bug in the game, report it using this form.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: dropdown
    id: version
    attributes:
      label: Game version
      description: The README.txt file shows the currently installed version. Check it there.
      options:
        - 0.1.3a (UNRELEASED, DONT USE YET)
        - 0.0.2a
        - 0.0.1a
      default: 1
    validations:
      required: true
  - type: input
    id: operating-system
    attributes:
      label: Operating system
      description: What operating system are you using?
    validations:
      required: true
  - type: textarea
    id: bug-info
    attributes:
      label: Bug Information
      description: Explain the bug in detail, and the expected behaviour.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: Explain how to reproduce the bug.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log file
      description: Please put the log file from your ``logs/`` folder in the exact same location as the game executable.
      placeholder: This currently only applies to v0.1.3a, which is currently unreleased.
      render: shell
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: a
      description: a
      options:
        - label: I have updated to the latest version to make sure my bug hasn't been fixed.
        required: true
